## Showing speed of Vectorization vs For Loop

In [1]:
import numpy as np

a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [22]:
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()

print(c)
print('Vectorized version: ' + str(1000*(toc-tic)) + 'ms')

c = 0
tic = time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc = time.time()

print(c)
print("For loop: " + str(1000*(toc-tic))+ 'ms')

250118.52785064938
Vectorized version: 1.9941329956054688ms
250118.5278506419
For loop: 493.6790466308594ms


In [23]:
A = np.array([[56.0, 0.0, 4.4, 68.0],[1.2,104.0,52.0,8.0],[1.8,135.0,99.0,0.9]])

print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [24]:
cal = A.sum(axis=0) #axis=0 means sum vertically.  Axis 1 would sum horizontally
print(cal)

[ 59.  239.  155.4  76.9]


In [26]:
percentage = 100*A/cal.reshape(1,4) #don't acutally need to reshape because cal is already a 1,4 matrix
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [27]:
b = np.random.randn(5) #makes five random gaussian variables

In [28]:
print(b)

[-0.41474724  0.22320345 -0.34253471  0.4758628  -0.21035594]


In [29]:
print(b.shape) #this is a rank 1 array

(5,)


In [30]:
print(b.T) #the transpose looks the same

[-0.41474724  0.22320345 -0.34253471  0.4758628  -0.21035594]


In [32]:
print(np.dot(b,b.T))

0.6098601134326935


In [33]:
b = np.random.rand(5,1)
print(b)

[[0.04104669]
 [0.58134036]
 [0.33338582]
 [0.89858912]
 [0.31497989]]


In [34]:
print(b.T)

[[0.04104669 0.58134036 0.33338582 0.89858912 0.31497989]]


In [35]:
print(np.dot(b,b.T))

[[0.00168483 0.0238621  0.01368439 0.03688411 0.01292888]
 [0.0238621  0.33795662 0.19381063 0.52238613 0.18311052]
 [0.01368439 0.19381063 0.1111461  0.29957687 0.10500983]
 [0.03688411 0.52238613 0.29957687 0.80746241 0.2830375 ]
 [0.01292888 0.18311052 0.10500983 0.2830375  0.09921233]]


Can use an assertion statement to make sure it's what we want

In [40]:
assert(b.shape == (5,1))

In [41]:
print(b.shape)

(5, 1)


In [45]:
b = b.reshape((5,1))

In [46]:
print(b.shape)

(5, 1)


In [47]:
a = np.random.randn(12288, 150) # a.shape = (12288, 150)
b = np.random.randn(150, 45) # b.shape = (150, 45)
c = np.dot(a,b)

In [48]:
print(c.shape)

(12288, 45)


In [50]:
d = np.random.randn(4, 3) # a.shape = (4, 3)
e = np.random.randn(3, 2) # b.shape = (3, 2)
f = d*e

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [51]:
a = np.random.randn(2, 3) # a.shape = (2, 3)
b = np.random.randn(2, 1) # b.shape = (2, 1)
c = a + b

In [52]:
print(c.shape)

(2, 3)


In [54]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b

In [55]:
print(c.shape)

(3, 3)


In [ ]:
a*b + a*c - b+c